_commit: v1.5.1
_src_path: gh:superlinear-ai/substrate
author_email: zcorrea357@gmail.com
author_name: Luiz Gustavo Corrêa Filho
project_description: Enterprise incident response platform integrated with MISP,MITRE
    ATT&CK
project_name: SentinelResponse
project_type: package
project_url: https://github.com/SentinelIQ/SentinelResponse
python_version: '3.10'
typing: strict
with_conventional_commits: true
with_typer_cli: false
