class Alert:
    """Represents a security alert.

    This class encapsulates the details of a security alert generated by the
    system. Each alert is characterized by a unique identifier, a descriptive
    message, and a severity level indicating the urgency or impact of the alert.

    Parameters
    ----------
    alert_id : int
        Unique identifier for the alert.
    message : str
        Descriptive message explaining the alert.
    severity : str
        Severity level of the alert (e.g., "Alta", "Média", "Baixa").

    Attributes
    ----------
    alert_id : int
        Unique identifier for the alert.
    message : str
        Descriptive message of the alert.
    severity : str
        Severity level of the alert.

    Examples
    --------
    >>> alert = Alert(alert_id=1, message="Login suspeito detectado", severity="Alta")
    >>> print(alert)
    Alert(id=1, severity='Alta')

    """

    def __init__(self, alert_id: int, message: str, severity: str):
        self.alert_id = alert_id
        self.message = message
        self.severity = severity

    def __repr__(self):
        return f"Alert(id={self.alert_id}, severity='{self.severity}')"
